services:
- type: web
name: link-redirector-api
env: node
plan: free
region: oregon


buildCommand: npm install && npm run build
startCommand: npm start


autoDeploy: true # ðŸ”¥ ESTO ES LO CLAVE


envVars:
- key: NODE_ENV
value: production


- key: https://ocxkbbccjatvlslycnad.supabase.co
sync: false


- key: sb_publishable_KtfaFAten99jAGlOGDZ3bA_QA7zXKg6
sync: false


- key: sb_secret_lASui-bYF3n3wjjpOYRKQQ_bpmRV7WE
sync: false


- key: http://localhost:5173
sync: false


- key: http://localhost:3001
sync: false